// <auto-generated />
using System;
using CourseWorkMailClient.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CourseWorkMailClient.Data.Migrations
{
    [DbContext(typeof(KeyDbContext))]
    [Migration("20211130161248_ExtendedTableOfKeysAndAddedInterlocatorTable")]
    partial class ExtendedTableOfKeysAndAddedInterlocatorTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CourseWorkMailClient.Domain.Keys.DESRsaKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DeathTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LifeTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("MessageId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrivateKey")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PublicKey")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DESRsaKeys");
                });

            modelBuilder.Entity("CourseWorkMailClient.Domain.Keys.Interlocutor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DESRsaKeyId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MD5RsaKeyId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DESRsaKeyId");

                    b.HasIndex("MD5RsaKeyId");

                    b.ToTable("Interlocutors");
                });

            modelBuilder.Entity("CourseWorkMailClient.Domain.Keys.MD5RsaKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DeathTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LifeTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("MessageId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrivateKey")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PublicKey")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MD5RsaKeys");
                });

            modelBuilder.Entity("CourseWorkMailClient.Domain.Keys.Interlocutor", b =>
                {
                    b.HasOne("CourseWorkMailClient.Domain.Keys.DESRsaKey", "DESRsaKey")
                        .WithMany("Interlocutors")
                        .HasForeignKey("DESRsaKeyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CourseWorkMailClient.Domain.Keys.MD5RsaKey", "MD5RsaKey")
                        .WithMany("Interlocutors")
                        .HasForeignKey("MD5RsaKeyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DESRsaKey");

                    b.Navigation("MD5RsaKey");
                });

            modelBuilder.Entity("CourseWorkMailClient.Domain.Keys.DESRsaKey", b =>
                {
                    b.Navigation("Interlocutors");
                });

            modelBuilder.Entity("CourseWorkMailClient.Domain.Keys.MD5RsaKey", b =>
                {
                    b.Navigation("Interlocutors");
                });
#pragma warning restore 612, 618
        }
    }
}
